server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/testdb_2
    username: root
    password: 691216



  redis:
    database: 0
    host: localhost
    port: 6379
    password: 691216
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 3000


  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: SPringBootV2
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20881
    scan: com.jiangwei.sg.service  #服务暴露与发现消费所在的package





mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true



